source 'http://rubygems.org'

gem 'delayed_job'
gem 'httparty'
gem 'jquery-rails'
gem 'memcache-client'
gem 'rails', '3.0.9'
gem 'simplecov', '>= 0.4.0', :require => false, :group => :test
gem 'sqlite3'
gem "webrat"
